// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-IrPU5v1KfuebtzBhz7O-qk_pBZmdAR4',
    appId: '1:290241650923:web:00e14adbcabc1009541eae',
    messagingSenderId: '290241650923',
    projectId: 'push-notification-85d52',
    authDomain: 'push-notification-85d52.firebaseapp.com',
    storageBucket: 'push-notification-85d52.appspot.com',
    measurementId: 'G-YMRHVD30K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3XQw8ejOvzK0YFHbEeF80ugtdD1VgE78',
    appId: '1:290241650923:android:b9cdc7d43d91867c541eae',
    messagingSenderId: '290241650923',
    projectId: 'push-notification-85d52',
    storageBucket: 'push-notification-85d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzdW38daGuqRVa2-C8k2vlOy70IGj5Y8U',
    appId: '1:290241650923:ios:37425da9acb5d156541eae',
    messagingSenderId: '290241650923',
    projectId: 'push-notification-85d52',
    storageBucket: 'push-notification-85d52.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzdW38daGuqRVa2-C8k2vlOy70IGj5Y8U',
    appId: '1:290241650923:ios:1ea208595955a28b541eae',
    messagingSenderId: '290241650923',
    projectId: 'push-notification-85d52',
    storageBucket: 'push-notification-85d52.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
